#!/bin/bash
echo "Running dotnet format on Lint.csproj..."
dotnet format src/Lint.csproj --verify-no-changes
if [ $? -ne 0 ]; then
    echo "Code formatting check failed. Run 'dotnet format src/Lint.csproj' to fix."
    exit 1
fi