name: "Documentation request"
description: Create a new ticket for a documentation.
title: "[Documentation] - <title>"
labels: [
  "documentation"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Описание"
      description: Опишите свою проблему
      placeholder: Краткое описание проблемы
    validations:
      required: true
  - type: dropdown
    id: documentationtype
    attributes:
      label: DocumentationType
      description: Где нужно поменять документацию
      options:
        - ReadMe
        - Wiki
        - Code
        - Other
      default: 0
    validations:
      required: true